PeerCert and PeerCertChain implementation for rustls
ntex-rs/ntex pull request #101
Opened 2022-01-27 14:20 UTC by Antiarchitect

Implement PeerCert and PeerCertChain for rustls server and client case.

2022-01-27 14:30 UTC, fafhrd91 requested changes
could you also add basic test

2022-01-27 14:30 UTC, fafhrd91 commented on ntex-tls/src/rustls/client.rs
> +pub struct PeerCert(pub Certificate);
this types should be common for client and server

2022-01-27 16:52 UTC, Antiarchitect commented
Locally I have:

```
failures:

---- test_rustls_string stdout ----
thread 'test_rustls_string' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: "invalid peer certificate contents: invalid peer certificate: UnsupportedCertVersion" })', ntex/tests/connect.rs:171:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.


failures:
    test_rustls_string

test result: FAILED. 6 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

Seems like a new cert.pem is needed generated properly. E.g. https://stackoverflow.com/a/18242720

2022-01-27 16:54 UTC, fafhrd91 commented
could you regenerate cert? also could you add entry to CHANGES.md

2022-01-27 16:58 UTC, Antiarchitect commented
Will try

2022-01-27 17:55 UTC, Antiarchitect commented
The test fails - will look at it tomorrow. If you have any ideas - any help would be appreciated.

2022-01-27 18:17 UTC, fafhrd91 commented
i will check tomorr

2022-01-28 08:45 UTC, fafhrd91 commented
you should use `pkcs8_private_keys` instead of `rsa_private_key`

2022-01-28 13:20 UTC, Antiarchitect commented
Seems like I use it already in connect.rs

2022-01-28 13:35 UTC, fafhrd91 commented
you beed to change it tests. seems key.pem is different format bow

2022-01-28 14:35 UTC, Antiarchitect commented
Fixed all other tests by changing rsa_private_keys to pcks8_private_keys everywhere. test_rustls_string still fails. If I `#[ignore]` it - all others pass. And I don't know where is the problem with it. Do I set Acceptor and test_server correct?

2022-01-28 15:58 UTC, fafhrd91 commented
I will check

2022-01-29 05:55 UTC, fafhrd91 commented
add ignore for now, i will debug later

2022-01-29 08:13 UTC, Antiarchitect commented
Tests go well on stable.

2022-01-29 08:26 UTC, fafhrd91 approved these changes

2022-01-29 08:27 UTC, fafhrd91 commented
thanks!

2022-01-29 08:27 UTC, merged

2022-01-30 14:49 UTC, fafhrd91 commented
new version is released

2022-01-30 23:34 UTC, Antiarchitect commented
@fafhrd91 Thank you! I have successfully upgraded my app to ntex 0.5.x.