[FEATURE] FnShutdown service with on_shutdown callback
ntex-rs/ntex pull request #163
Opened 2023-01-21 12:52 UTC by leon3s

Hey following our conversation i tried to implement the `FnShutdown` Service.
Maybe i should have used `FnServiceFactory` instead of `Service` ?

2023-01-22 03:59 UTC, fafhrd91 commented
fn_shutdown should provide only shutdow callback and nothing else. usage would be 

```rust
pipeline(srv).and_then(fn_shutdown(|| some code))
```

2023-01-22 13:43 UTC, leon3s commented
I see, sorry i'm not 100% familiar with all your API, i'm gonna change that!

2023-01-22 14:56 UTC, leon3s commented
I tried to prototype it the way you wanted in previous comments

```rust
FnShutdown<S, F: FnOnce>
```

But i had to implement the `call` method of the `Service` trait and keep traking the Error.
Im not sure about the :
```rust
Req: Clone + 'static 
```
aswell but i didn't find other way to make it compile..

2023-01-23 09:42 UTC, fafhrd91 commented
here is working code, I think it would be better to wrap other service and make FnShutdown<S, F>{..}
in that case call method would actually call inner service, otherwise it just return result back

```rust

use std::{cell::Cell, future::ready, future::Ready, marker, task::Context, task::Poll};

use crate::Service;

pub struct FnShutdown<Req, Err, F = fn()> {
    f_shutdown: Cell<Option<F>>,
    _t: marker::PhantomData<(Req, Err)>,
}

impl<Req, Err, F> Service<Req> for FnShutdown<Req, Err, F>
where
    F: FnOnce(),
{
    type Response = Req;
    type Error = Err;
    type Future<'f> = Ready<Result<Req, Err>> where Self: 'f, Req: 'f;

    #[inline]
    fn poll_shutdown(&self, _: &mut Context<'_>) -> Poll<()> {
        if let Some(f) = self.f_shutdown.take() {
            (f)()
        }
        Poll::Ready(())
    }

    fn call(&self, req: Req) -> Self::Future<'_> {
        ready(Ok(req))
    }
}
```

2023-01-23 13:01 UTC, leon3s commented
Got it thank you

2023-01-23 16:13 UTC, fafhrd91 requested changes
could you also add entry to CHANGES, and bump version to 1.0.1

lgtm.

2023-01-23 16:13 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +use std::{
could you split into separate lines, I don't like such formatting

2023-01-23 16:13 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +/// Create `FnShutdown` service with a on_shutdown callback.
could you add detail doc, similar to fn_service

2023-01-23 16:13 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +impl<Req, Err, F> FnShutdown<Req, Err, F> {
could you also add Clone implementation if F: Clone

2023-01-23 16:13 UTC, fafhrd91 commented on ntex-service/src/lib.rs
> +pub use self::fn_shutdown::fn_shutdown;
also import FnShutdown in dev module

2023-01-23 18:42 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +    F: FnOnce(),
this should be `F: Clone`

2023-01-23 18:42 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +            f_shutdown: Cell::new(self.f_shutdown.take()),
this moves function, you need to clone it

2023-01-23 18:50 UTC, fafhrd91 commented on ntex-service/src/fn_shutdown.rs
> +pub struct FnShutdown<Req, Err, F = fn()> {
remove default `= fn()` arg, FnShutdown won't have default F ever

2023-01-23 20:47 UTC, leon3s commented
Something like that ?

2023-01-24 07:42 UTC, fafhrd91 approved these changes
lgtm

2023-01-24 07:42 UTC, merged

2023-01-24 07:42 UTC, fafhrd91 commented
good work!